// Copyright (c) 2010, Amar Takhar <verm@aegisub.org>
//
// Permission to use, copy, modify, and distribute this software for any
// purpose with or without fee is hereby granted, provided that the above
// copyright notice and this permission notice appear in all copies.
//
// THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
// WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
// MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
// ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
// WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
// ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
// OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
//
// $Id$

/// @file proto.h
/// @brief Command prototypes.
/// @ingroup command

#include "aegisub/context.h"

#define CMD_CLASS(a) \
	class a: public Command { \
	public: \
		static const char* name(); \
		wxString StrMenu() const; \
		wxString StrDisplay() const; \
		wxString StrHelp() const; \
		void operator()(agi::Context *c); \
	};
namespace cmd {
	CMD_CLASS(am_manager)
	CMD_CLASS(app_about)
	CMD_CLASS(app_display_audio_subs)
	CMD_CLASS(app_display_full)
	CMD_CLASS(app_display_subs)
	CMD_CLASS(app_display_video_subs)
	CMD_CLASS(app_exit)
	CMD_CLASS(app_language)
	CMD_CLASS(app_log)
	CMD_CLASS(app_new_window)
	CMD_CLASS(app_options)
	CMD_CLASS(app_updates)
	CMD_CLASS(audio_close)
	CMD_CLASS(audio_open)
	CMD_CLASS(audio_open_blank)
	CMD_CLASS(audio_open_noise)
	CMD_CLASS(audio_open_video)
	CMD_CLASS(audio_view_spectrum)
	CMD_CLASS(audio_view_waveform)
	CMD_CLASS(edit_line_copy)
	CMD_CLASS(edit_line_cut)
	CMD_CLASS(edit_line_delete)
	CMD_CLASS(edit_line_duplicate)
	CMD_CLASS(edit_line_duplicate_shift)
	CMD_CLASS(edit_line_join_as_karaoke)
	CMD_CLASS(edit_line_join_concatenate)
	CMD_CLASS(edit_line_join_keep_first)
	CMD_CLASS(edit_line_paste)
	CMD_CLASS(edit_line_paste_over)
	CMD_CLASS(edit_line_recombine)
	CMD_CLASS(edit_line_split_by_karaoke)
	CMD_CLASS(edit_line_swap)
	CMD_CLASS(edit_redo)
	CMD_CLASS(edit_search_replace)
	CMD_CLASS(edit_undo)
	CMD_CLASS(grid_line_next)
	CMD_CLASS(grid_line_prev)
	CMD_CLASS(grid_tag_cycle_hiding)
	CMD_CLASS(grid_tags_hide)
	CMD_CLASS(grid_tags_show)
	CMD_CLASS(grid_tags_simplify)
	CMD_CLASS(help_bugs)
	CMD_CLASS(help_contents)
	CMD_CLASS(help_files)
	CMD_CLASS(help_forums)
	CMD_CLASS(help_irc)
	CMD_CLASS(help_website)
	CMD_CLASS(keyframe_close)
	CMD_CLASS(keyframe_open)
	CMD_CLASS(keyframe_save)
	CMD_CLASS(main_audio)
	CMD_CLASS(main_automation)
	CMD_CLASS(main_edit)
	CMD_CLASS(main_edit_sort_lines)
	CMD_CLASS(main_file)
	CMD_CLASS(main_help)
	CMD_CLASS(main_main_subtitle)
	CMD_CLASS(main_subtitle_insert_lines)
	CMD_CLASS(main_subtitle_join_lines)
	CMD_CLASS(main_subtitle_sort_lines)
	CMD_CLASS(main_timing)
	CMD_CLASS(main_timing_make_times_continous)
	CMD_CLASS(main_video)
	CMD_CLASS(main_video_set_zoom)
	CMD_CLASS(main_view)
	CMD_CLASS(medusa_enter)
	CMD_CLASS(medusa_next)
	CMD_CLASS(medusa_play)
	CMD_CLASS(medusa_play_after)
	CMD_CLASS(medusa_play_before)
	CMD_CLASS(medusa_previous)
	CMD_CLASS(medusa_shift_end_back)
	CMD_CLASS(medusa_shift_end_forward)
	CMD_CLASS(medusa_shift_start_back)
	CMD_CLASS(medusa_shift_start_forward)
	CMD_CLASS(medusa_stop)
	CMD_CLASS(recent_audio)
	CMD_CLASS(recent_keyframe)
	CMD_CLASS(recent_subtitle)
	CMD_CLASS(recent_timecode)
	CMD_CLASS(recent_video)
	CMD_CLASS(subtitle_attachment)
	CMD_CLASS(subtitle_find)
	CMD_CLASS(subtitle_find_next)
	CMD_CLASS(subtitle_insert_after)
	CMD_CLASS(subtitle_insert_after_videotime)
	CMD_CLASS(subtitle_insert_before)
	CMD_CLASS(subtitle_insert_before_videotime)
	CMD_CLASS(subtitle_new)
	CMD_CLASS(subtitle_open)
	CMD_CLASS(subtitle_open_charset)
	CMD_CLASS(subtitle_open_video)
	CMD_CLASS(subtitle_properties)
	CMD_CLASS(subtitle_save)
	CMD_CLASS(subtitle_save_as)
	CMD_CLASS(subtitle_select_visiblek)
	CMD_CLASS(subtitle_spellcheck)
	CMD_CLASS(subtitle_tags_show)
	CMD_CLASS(time_continous_end)
	CMD_CLASS(time_continous_start)
	CMD_CLASS(time_frame_current)
	CMD_CLASS(time_shift)
	CMD_CLASS(time_snap_end_video)
	CMD_CLASS(time_snap_frame)
	CMD_CLASS(time_snap_scene)
	CMD_CLASS(time_snap_start_video)
	CMD_CLASS(time_sort_end)
	CMD_CLASS(time_sort_start)
	CMD_CLASS(time_sort_style)
	CMD_CLASS(timecode_close)
	CMD_CLASS(timecode_open)
	CMD_CLASS(timecode_save)
	CMD_CLASS(tool_assdraw)
	CMD_CLASS(tool_export)
	CMD_CLASS(tool_font_collector)
	CMD_CLASS(tool_line_select)
	CMD_CLASS(tool_resampleres)
	CMD_CLASS(tool_style_assistant)
	CMD_CLASS(tool_style_manager)
	CMD_CLASS(tool_time_kanji)
	CMD_CLASS(tool_time_postprocess)
	CMD_CLASS(tool_translation_assistant)
	CMD_CLASS(video_aspect_cinematic)
	CMD_CLASS(video_aspect_custom)
	CMD_CLASS(video_aspect_default)
	CMD_CLASS(video_aspect_full)
	CMD_CLASS(video_aspect_wide)
	CMD_CLASS(video_close)
	CMD_CLASS(video_detach)
	CMD_CLASS(video_details)
	CMD_CLASS(video_focus_seek)
	CMD_CLASS(video_frame_next)
	CMD_CLASS(video_frame_play)
	CMD_CLASS(video_frame_prev)
	CMD_CLASS(video_jump)
	CMD_CLASS(video_jump_end)
	CMD_CLASS(video_jump_start)
	CMD_CLASS(video_open)
	CMD_CLASS(video_open_dummy)
	CMD_CLASS(video_show_overscan)
	CMD_CLASS(video_zoom_100)
	CMD_CLASS(video_zoom_200)
	CMD_CLASS(video_zoom_50)
	CMD_CLASS(video_zoom_in)
	CMD_CLASS(video_zoom_out)
} // namespace cmd
